// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFREqOpB2Im73gopfzCWapvqt0lFRRg6Q',
    appId: '1:904571812124:web:6b60cc9ce0e313a19b62d9',
    messagingSenderId: '904571812124',
    projectId: 'socialmedia-9d097',
    authDomain: 'socialmedia-9d097.firebaseapp.com',
    storageBucket: 'socialmedia-9d097.appspot.com',
    measurementId: 'G-KN73HD5QLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrS0smgozmx9pZVFmqo-ky6b-vtYrHlMs',
    appId: '1:904571812124:android:1841824288a207d19b62d9',
    messagingSenderId: '904571812124',
    projectId: 'socialmedia-9d097',
    storageBucket: 'socialmedia-9d097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCshoNao00qGvd3XmVzYfPGHql-fVgfsds',
    appId: '1:904571812124:ios:9366db7077ffa3a59b62d9',
    messagingSenderId: '904571812124',
    projectId: 'socialmedia-9d097',
    storageBucket: 'socialmedia-9d097.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCshoNao00qGvd3XmVzYfPGHql-fVgfsds',
    appId: '1:904571812124:ios:32ac230a3d4c16be9b62d9',
    messagingSenderId: '904571812124',
    projectId: 'socialmedia-9d097',
    storageBucket: 'socialmedia-9d097.appspot.com',
    iosBundleId: 'com.example.socialmedia.RunnerTests',
  );
}
